---
- name: This sets up an httpd webserver
  hosts: 18.221.156.4
  become: true
  tasks:
  - name: Install the nginx rpm
    yum:
      name: httpd
      state: present
  - name: start the nginx service
    service:
      name: httpd
      state: started
